#!/bin/bash
# https://masawada.hatenablog.jp/entry/2021/02/24/123000

set -e

if ! type tree > /dev/null 2>&1; then
  echo 'command not found: tree'
  exit 1;
fi

git ls-files | tree --fromfile=. "$@"
