---
font:
    size: 8.0
    normal:
        family: DroidSansM Nerd Font
        style: Regular
        # bold:
        #     family: DroidSansM Nerd Font
        #     style: Bold
        # italic:
        #     family: DroidSansM Nerd Font
        #     style: Italic
window:
    dimensions:
        columns: 120
        lines: 120
