name: Shell Script Linting

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up shellcheck and yamllint
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
        pip install yamllint

    - name: Run linting
      run: |
        # Your shell script content goes here
        /bin/bash -c '
          shell_file_list=("~/.bash_aliases" "~/.bashrc")

          while IFS= read -r line; do
            src_file=$(echo "$line" | awk '\''{print $4}'\'')

            if [ -z "$src_file" ]; then
              continue
            fi

            src_path="${src_file/#\~/$HOME}"
            if [ -e $src_path ]; then
              
              # 予め定義しておいたshellscriptファイル
              # ~/.bash_aliasesは実行形式でもないしshebangもないためshellファイルであるかの判定が難しいため手動定義
              if [[ "${shell_file_list[@]}" =~ "$src_file" ]];then
                shellcheck "$src_path"
              fi

              # 拡張子で判定できるものは拡張子をもとにファイルに沿ったリントをかける
              case "${src_path##*/}" in
                *.sh)
                  shellcheck "$src_path"
                  ;;
                *.yaml | *.yml)
                  yamllint "$src_path"
                  ;;
              esac
            fi
          done < dotfilesLink.sh
        '

